
package com.lxc.learn.webservice.simple.clien.notuse;

import com.lxc.learn.webservice.simple.clien.SimpleWebService;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleWebServiceService", targetNamespace = "http://serve.simple.webservice.learn.lxc.com/", wsdlLocation = "http://localhost:9090/SimpleWebService?wsdl")
public class SimpleWebServiceService
    extends Service
{

    private final static URL SIMPLEWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLEWEBSERVICESERVICE_EXCEPTION;
    private final static QName SIMPLEWEBSERVICESERVICE_QNAME = new QName("http://serve.simple.webservice.learn.lxc.com/", "SimpleWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/SimpleWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLEWEBSERVICESERVICE_WSDL_LOCATION = url;
        SIMPLEWEBSERVICESERVICE_EXCEPTION = e;
    }

    public SimpleWebServiceService() {
        super(__getWsdlLocation(), SIMPLEWEBSERVICESERVICE_QNAME);
    }

    public SimpleWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLEWEBSERVICESERVICE_QNAME, features);
    }

    public SimpleWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLEWEBSERVICESERVICE_QNAME);
    }

    public SimpleWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLEWEBSERVICESERVICE_QNAME, features);
    }

    public SimpleWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleWebService
     */
    @WebEndpoint(name = "SimpleWebServicePort")
    public SimpleWebService getSimpleWebServicePort() {
        return super.getPort(new QName("http://serve.simple.webservice.learn.lxc.com/", "SimpleWebServicePort"), SimpleWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleWebService
     */
    @WebEndpoint(name = "SimpleWebServicePort")
    public SimpleWebService getSimpleWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serve.simple.webservice.learn.lxc.com/", "SimpleWebServicePort"), SimpleWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLEWEBSERVICESERVICE_EXCEPTION!= null) {
            throw SIMPLEWEBSERVICESERVICE_EXCEPTION;
        }
        return SIMPLEWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
