spring:
  application:
    name: learn-redis

  # 数据库配置
  redis:
    database: 0
    host: 172.16.123.20
    password: VP123club


  profiles:
    active:
      - common
      - web
test:
  pubsub: false
  simple: false