server:
  port: 10011

eureka:
  instance:
    hostname: nodeB
    #prefer-ip-address: false
  client:
  #是否注册自己进入注册中心
    register-with-eureka: true
    #要不要去注册中心获取其他服务的地址
    fetch-registry: true
    serviceUrl:
      defaultZone: http://nodeA:10010/eureka/

