spring:
  #application:
    #name: learn-junit
  # 数据库配置
  profiles:
    include:
      - druid
  datasource:
    jmx-enabled: false
    name: test
    url: jdbc:mysql://localhost:3333/learn?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456!!
#    url: jdbc:mysql://localhost:3306/learn?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
#    username: root
#    password: 123456
    #type: com.alibaba.druid.pool.DruidDataSource
    #type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    druid:
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      # encrypt password
      #filters: config,stat,wall,log4j
      connection-properties: "config.decrypt=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
      use-global-data-source-stat: true
#  thymeleaf:
#    cache: false
#    prefix: classpath:/static/
#    suffix: .html
#    mode: LEGACYHTML5

#  devtools:
#    livereload:
#      enabled: true #是否支持livereload
#      port: 35729
#    restart:
#      enabled: true #是否支持热部署

  http:
    multipart:
      enabled: false

log:
  package: com.lxc.learn.junit
  level: debug

task:
  switch: false

# 数组配置
test:
  arr:
    - 1
    - 2
custom:
  test-varilable: 9099
  task: 0009
server:
  port: 9999
  tomcat:
    accept-count: 100 #等待队列长度：队列做缓冲池用，但也不能无限长，消耗内存，出入队列也耗cpu。
    max-connections: 10000 #最大可被连接数，默认为10000
    max-threads: 1000  #最大工作线程数
    min-spare-threads: 10 #最小工作线程数

config:
  switch: true
  prefix:
    userName: lxc
    password: 02
    test: test
mybatis:
  typeAliasesPackage: "com.lxc.learn.junit.entity"
  #checkConfig-location : false
  mapper-locations: "classpath:com/lxc/learn/junit/mapper/xml/*Mapper.xml"


mybatisplus:
  enabled: true
  generic:
    enabled: true
  dialectType: mysql


# 启用端点 env https://blog.csdn.net/fly910905/article/details/78580895
management:
  security:
    enabled: true
    user:
      name: admin
      password: 123456
    role: ADMIN
  endpoints:
#    web:
#      exposure:
##        include: * 此配置不能开启所有端点？
#        include: info, health, beans, env, metrics
    web:
      exposure:
      # exclude: '*'
        include: '*'
      base-path: /actuator  # 配置 Endpoint 的基础路径
      cors: # 配置跨域资源共享
        #allowed-origins: *
        allowed-methods: GET,POST
    enabled-by-default: true # 修改全局 endpoint 默认设置
  endpoint:
    health:
      show-details: "ALWAYS"

#management:
#   endpoint:
#      health:
#        show-details: "ALWAYS"