datasource:
  url: jdbc:mysql://mysql-prod:3306/learn?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
  userName: root
  password: 123456
  
  
sms:
  host: sms-prod
  port: 10999  
