datasource:
  url: jdbc:mysql://mysql-dev111:3306/learn?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
  userName: root
  password: 123456


sms:
  host: sms-dev1212
  port: 10999
