server:
  port: 3302
# 其中 management 是关于 actuator 相关的，接下来自动刷新配置的时候需要使用。
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

# ? 此处配置无效，必须配置在bootstrap.yml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10011/eureka/


# 部分是当无法读取配置中心的配置时，可再下面配置变量，以免项目无法启动。

