spring:
  application:
    name: eureka-client-order

server:
  port: 3001
# spring.cloud.circuit.breaker.enabled
  cloud:
    circuit:
      breaker:
        enabled: true
        requestVolumeThreshold: 2 #允许最小访问请求数量,
        sleepWindowInMilliseconds: 5000  #休眠时间窗的时间范围，单位毫秒
        errorThresholdPercentage:  50 #开启熔断的错误率，


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10011/eureka/,http://localhost:10010/eureka/
  instance:
    #prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5 #服务刷新时间配置，每隔这个时间会主动心跳一次默认30s
feign:
  hystrix:
    enabled: true #关闭时，服务超时调用方也会提示超时，调用方没法进行服务降级处理
  httpclient:
    enabled: true
  compression:
    request:
      enabled: true       #请求和响应GZIP压缩支持
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
      #org.springframework.cloud.openfeign.FeignClientProperties
  client:
    config:
      default:           #服务名，填写default为所有服务
        connectTimeout: 30000 #超时时间
        readTimeout: 30000  #feign 超时时间,超时后自动降级

# HystrixCommandProperties
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
          #大于这个时间，会服务降级
            timeoutInMilliseconds: 15000
            #服务熔断条件
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 2
        sleepWindowInMilliseconds: 2000
        errorThresholdPercentage: 50

#ribbon:
#  ServerListRefreshInterval: 5000 #eureka客户端ribbon刷新时间默认30s
#  ReadTimeout: 10000
#  ConnectTimeout: 10000
#  MaxAutoRetries: 0 #同一台实例最大重试次数,不包括首次调用
#  MaxAutoRetriesNextServer: 0 #重试负载均衡其他的实例最大重试次数,不包括首次调用
#  OkToRetryOnAllOperations: false  #是否所有操作都重试


ribbon:
  # 开启eureka与ribbon的集成
  eureka:
    enabled: true
  # 暂不开启熔断机制
  hystrix:
    enabled: false
  # 配置ribbon默认的超时时间
  ConnectTimeout: 20000
  ReadTimeout: 20000

